# Stage 1
FROM node:16-alpine as build-stage
WORKDIR /client
COPY package.json .
COPY package-lock.json .
RUN npm install
COPY . .
RUN npm run build
# Stage 2
FROM nginx:1.23.0-alpine
COPY --from=build-stage /client/build /usr/share/nginx/html
COPY nginx/nginx.conf /etc/nginx/conf.d/default.conf

# EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]